# Lab 4-2. Loading Data From File

- 파일로 부터 데이터 읽어오기

- example: data-01-test-score.csv

```
#EXAM1,EXAM2,EXAM3,FINAL
73,80,75,152
93,88,93,185
89,91,90,180
96,98,100,196
73,66,55,142
53,46,55,101
```

In [1]:
import numpy as np
xy = np.loadtxt('./data/data-01-test-score.csv',delimiter=',', dtype=np.float32)

In [2]:
x_data=xy[:,0:-1]

x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   55.],
       [  53.,   46.,   55.]], dtype=float32)

In [3]:
y_data=xy[:,[-1]]

y_data

array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.]], dtype=float32)

In [4]:
print(x_data.shape, x_data)
print(y_data.shape, y_data)

(6, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   55.]
 [  53.   46.   55.]]
(6, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]


## Slicing in python

- python의 리스트의 강력한 기능

In [5]:
nums = [1, 2, 3, 4, 5]

In [6]:
nums

[1, 2, 3, 4, 5]

In [7]:
nums[2:4]

[3, 4]

In [8]:
nums[2:]

[3, 4, 5]

In [9]:
nums[:2]

[1, 2]

In [10]:
nums[:]

[1, 2, 3, 4, 5]

In [11]:
nums[:-1]

[1, 2, 3, 4]

In [12]:
nums[2:4] = [8,9]
nums

[1, 2, 8, 9, 5]

In [13]:
nums

[1, 2, 8, 9, 5]

## Indexing, Slicing, Iterating in numpy

- $:$는 $...$로 대체될 수 잇음

In [14]:
a = np.array([1, 2, 3, 4, 5])
a[1:3]

array([2, 3])

In [15]:
a[-1]

5

In [16]:
a[0:2]=9

In [17]:
a

array([9, 9, 3, 4, 5])

In [18]:
b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

b[:, 1]

array([ 2,  6, 10])

In [19]:
b[:,-1]

array([ 4,  8, 12])

In [20]:
b[:,[-1]]

array([[ 4],
       [ 8],
       [12]])

In [21]:
b[-1,:]

array([ 9, 10, 11, 12])

In [22]:
b[-1,...]

array([ 9, 10, 11, 12])

In [23]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## loading from file

In [24]:
import numpy as np

In [25]:
!ls -al data


total 8
drwxr-xr-x  6 taewan users  204 Jun  1 01:25 .
drwxr-xr-x 19 taewan users  646 Jun  1 01:21 ..
drwxr-xr-x  2 taewan users   68 May 31 09:26 .ipynb_checkpoints
-rw-r--r--  1 taewan users  103 Jun  1 01:21 data-01-test-score.csv
-rw-r--r--  1 taewan users 3184 Jun  1 01:24 data_1.csv
-rw-r--r--  1 taewan users    0 Jun  1 01:24 data_2.csv


In [26]:
xy = np.loadtxt("./data/data-01-test-score.csv", delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, -1]

In [27]:
x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   55.],
       [  53.,   46.,   55.]], dtype=float32)

In [28]:
y_data

array([ 152.,  185.,  180.,  196.,  142.,  101.], dtype=float32)

In [29]:
print(x_data.shape, y_data.shape)

(6, 3) (6,)


### updated code

In [30]:
import tensorflow as tf
import numpy as np

In [31]:
xy = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [32]:
x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   55.],
       [  53.,   46.,   55.]], dtype=float32)

In [33]:
y_data

array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.]], dtype=float32)

In [34]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [35]:
hypothesis = tf.matmul(X, W) + b

In [36]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [37]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [38]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [39]:
for step in range(100001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 20000 == 0:
        print(cost_val, hy_val)

128772.0 [[-196.63195801]
 [-216.45535278]
 [-223.81983948]
 [-242.10472107]
 [-156.37097168]
 [-113.21675873]]
0.976894 [[ 152.60157776]
 [ 183.81851196]
 [ 180.92503357]
 [ 194.96876526]
 [ 142.06488037]
 [ 102.47655487]]
0.960598 [[ 152.63470459]
 [ 183.79957581]
 [ 180.94218445]
 [ 194.98530579]
 [ 142.05340576]
 [ 102.41405487]]
0.945515 [[ 152.62283325]
 [ 183.80943298]
 [ 180.94439697]
 [ 194.99205017]
 [ 142.05204773]
 [ 102.39898682]]
0.930604 [[ 152.61094666]
 [ 183.81932068]
 [ 180.94664001]
 [ 194.99882507]
 [ 142.0506897 ]
 [ 102.38394928]]
0.916125 [[ 152.59921265]
 [ 183.82904053]
 [ 180.94880676]
 [ 195.00543213]
 [ 142.04934692]
 [ 102.36920166]]


## Prediction

In [40]:
sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]})

array([[ 179.61494446]], dtype=float32)

In [41]:
sess.run(hypothesis, feed_dict={X:[[90, 100, 80],[60,70,110]]})

array([[ 188.6000824 ],
       [ 129.58557129]], dtype=float32)

## Queue Runners

![](./images/10/queue_runner.jpg)

- 파일명을 익어서 파일명 큐에 저장
- reader를 만들어서 파일을 읽어 데이터를 리코드한 후 데이터를 queue에 저장
- queue에서 데이터를 읽어서 학습시킴
- 이것을 batch라고 함

![](./images/10/queue_runner.jpg)

![](./images/10/train.batch.jpg)

## final code

In [ ]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['./data/data_1.csv','./data/data_2.csv'], 
                                                shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

recode_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=recode_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(20001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    #cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    #print(step, cost_val, hy_val)
    print(x_batch, y_batch)
    

In [ ]:
coord.request_stop()
coord.join(threads)

## shuffle_batch

```
min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tr.train.shuffle_batch(
  [example, label],batch_size=batch_size, 
  capacity=capacity,
  min_after_dequeue=min_after_dequeu)
```

- https://www.tensorflow.org/programmers_guide/reading_data

- 마지막을 코드 실행 실폐
- 추후 다시 알아볼것


## last update

In [ ]:
import datetime
print(datetime.datetime.now())