# Logistic Regression

$$ H(X) = \frac{1}{1+e^{-W^TX}} \\
0 < H(x) < 1
$$

$$
C(H(x), y) = -ylog(H(x)) - (1-y)log(1-H(x))
$$

$$ W := W - \alpha\frac{\delta}{\delta W}cost(W)$$ 

![](./images/13/descent.jpg)

## training data

In [2]:
import tensorflow as tf

x_data = [[1, 2],[2, 3],[3, 1],[4, 3],[5, 3],[6, 2]]
y_data = [[0],[0],[0],[1],[1],[1]]

X=tf.placeholder(tf.float32, shape=[None, 2]) # shape 에 주의 할 것, column 수:2
Y=tf.placeholder(tf.float32, shape=[None, 1]) # column 수:1

In [3]:
W = tf.Variable(tf.random_normal([2, 1]),name='weight') #2: 유입수-X에 맞춤, 1:출력수-Y에 맞춤 
b = tf.Variable(tf.random_normal([1]), name='bias') # 출력 갯수에 맞춤

$ H(X) = \frac{1}{1+e^{-W^TX}} $

In [39]:
hypothesis = tf.sigmoid(tf.matmul(X, W)+b)

In [40]:
#직접 구현 sigmoid 직접 구현
#hypothesis = tf.div(1., 1.+tf.exp(tf.matmul(X, W)+b))

$
cost(W) = -\frac{1}{m}\sum{ylog(H(x)) + (y-1)log(1-H(x))}
$


In [41]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))

$ W := W - \alpha\frac{\delta}{\delta W}cost(W)$

In [47]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [48]:
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [51]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print(step, cost_val)
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print('hypothesis:\n',h, '\ncorrent:\n',c, '\naccuracy\n',a)

0 1.88123
2000 0.0844577
4000 0.046473
6000 0.032243
8000 0.0247329
10000 0.0200768
hypothesis:
 [[  2.84853420e-04]
 [  3.19707915e-02]
 [  3.94559093e-02]
 [  9.55725372e-01]
 [  9.98191297e-01]
 [  9.99678731e-01]] 
corrent:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
accuracy
 1.0


## Classifying diabetes

In [77]:
import tensorflow as tf
import numpy as np

In [78]:
xy = np.loadtxt('./data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)

In [79]:
x_data= xy[:,:-1]
y_data= xy[:,[-1]]

In [80]:
len(x_data)

759

In [88]:
X = tf.placeholder(tf.float32, shape=[None, 8]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight') # 유입 8개 출력 1개
b = tf.Variable(tf.random_normal([1]), name='bias')

In [82]:
hypothesis = tf.sigmoid(tf.matmul(X, W)+b)

In [83]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))

In [84]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

In [85]:
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy= tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [86]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed={X:x_data, Y:y_data}
    for step in range(200001):
        sess.run(train, feed_dict=feed)
        if step % 40000 == 0 :
            print(step, sess.run(cost, feed_dict=feed))
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print('\nHypothesis\n', c, '\nAccuracy\n',a)

0 0.745158
40000 0.502569
80000 0.482785
120000 0.477573
160000 0.475262
200000 0.474001

Hypothesis
 [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [

## last update

In [89]:
import datetime
print(datetime.datetime.now())

2017-06-02 07:22:07.550874
